Repository algorithm0r/SuperMarioBros, pull requests merged in 2021-02, with the labels that each got.

#4 Create a pull request template
  .github/pull_request_template.md
Labels: PR: NEED REVIEW

#18 Closes #16
  bricks.js
  enemies.js
  sceneManager.js
Labels: PR: NEED REVIEW

#23 Created the title screen and transitions between levels.
  .vs/Mario/v16/.suo
  .vs/slnx.sqlite
  gameengine.js
  index.html
  levels.js
  main.js
  mario.js
  sceneManager.js
  sprites/title.png
  transition.js
Labels: ISSUE: UI/HUD, ISSUE: levels, ISSUE: map-transitions, PR: NEED REVIEW

#21 GH actions now should work on master branch
  .github/workflows/node.js.yml
  .gitignore
  package-lock.json
  package.json
  test/test.js
Labels: PR: NEED REVIEW

#25 Avatarabo/firemario
  .DS_Store
  bricks.js
  enemies.js
  items.js
  mario.js
Labels: ISSUE: mario, ISSUE: power-ups, PR: READY TO MERGE, PR: REVIEWED

#32 Added the koopa shell to the game
  enemies.js
  mario.js
Labels: PR: READY TO MERGE, PR: REVIEWED

#24 Seoungdeok jeon/fire bar
  enemies.js
  main.js
  mario.js
  sceneManager.js
  sprites/firebar_fire.png
Labels: PR: READY TO MERGE, PR: REVIEWED
