Repository algorithm0r/SuperMarioBros, pull requests merged in 2021-03, with the labels that each got.

#27 Algorithm0r/sound music
  .vs/Mario/v16/.suo
  .vs/slnx.sqlite
  assetmanager.js
  audio/1-up.mp3
  audio/block.mp3
  audio/bump.wav
  audio/coin.mp3
  audio/fireball.mp3
  audio/fireworks.mp3
  audio/flagpole.mp3
  audio/game-over.mp3
  audio/level-clear.mp3
  audio/life-lost.mp3
  audio/pipe.mp3
  audio/power-up-appears.mp3
  audio/power-up.mp3
  audio/small-jump.mp3
  audio/stomp.mp3
  audio/super-jump.mp3
  bricks.js
  index.html
  levels.js
  main.js
  mario.js
  music/castle-hurry.mp3
  music/castle.mp3
  music/invincible.mp3
  music/overworld-hurry.mp3
  music/overworld.mp3
  music/underworld-hurry.mp3
  music/underworld.mp3
  music/waterworld-hurry.mp3
  music/waterworld.mp3
  sceneManager.js
Labels: ISSUE: audio, PR: REVIEWED

#28 Added mario - piranha plant interactions
  enemies.js
  items.js
Labels: PR: REVIEWED

#29 added level 1-2 underground + bonus layout
  levels.js
Labels: PR: REVIEWED

#33 Basic four-shard exploding bricks. Needs spin animation for shards.
  bricks.js
  mario.js
Labels: PR: REVIEWED

#31 Adding hammer brother **PR: NEED REVIEW**
  enemies.js
Labels: ISSUE: enemies, PR: REVIEWED

#34 Moving platforms
  bricks.js
  levels.js
  mario.js
  sceneManager.js
Labels: PR: REVIEWED

#30 Palette switching
  .vscode/settings.json
  bricks.js
  levels.js
  main.js
  sceneManager.js
  sprites/underground_bricksolod.png
  sprites/underground_stuff.png
Labels: PR: READY TO MERGE, PR: REVIEWED
